# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: "Delegación EII"
title_separator: "-"
email: alumnos.eii@uva.es
description: "Delagación de Alumnos de la EII"
url: http://alumnos.eii.uva.es # the base hostname & protocol for your site, e.g. http://example.com
baseurl:
locale: "es-ES"
og_image: /assets//logo/logoDele.jpg
twitter: DELE_EII_UVA
facebook: DELE.EII.UVA
app_id:
telegram: Dele_EII
canalTelegram: Dele_EII_UVA
social:
  type                   : Organization # Person or Organization (defaults to Person)
  name                   : # If the user or organization name differs from the site's name
  links: # An array of links to social media profiles

# Build settings
markdown: kramdown
highlighter: rouge
kramdown:
  # parse markdown inside block-level HTML tag
  parse_block_html: true

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji

# Outputting
paginate: 9 # amount of posts to show
paginate_path: /noticias/:num/
timezone: Europe/Madrid # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

# Defaults
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: posts

include:
  - _pages
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

keep_files: [media, assets/logo, assets/gif]

prose:
  rooturl: '_posts'
  siteurl: 'http://alumnos.eii.uva.es/'
  relativeLinks: 'http://alumnos.eii.uva.es/links.jsonp'
  media: 'media'
  metadata:
    _posts:
      - name: "layout"
        field:
          element: "hidden"
          value: "posts"
      - name: "disqus"
        field:
          element: "checkbox"
          label: "Comentarios"
          value: true
      - name: "image"
        field:
          element: "text"
          label: "image"
          value: /assets/gif/timelapse.gif
      - name: "published"
        field:
          element: "checkbox"
          label: "Publicar"
          value: false
